---
abstract: 'application for pasting to and reading from sprunge.us'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.82
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pastebin-sprunge
requires:
  Getopt::Long: 0
  Pod::Usage: 0
  WWW::Pastebin::Sprunge::Create: 0
  WWW::Pastebin::Sprunge::Retrieve: 0
  perl: 5.006
  perl5i::2: 0
resources:
  bugtracker: https://github.com/doherty/App-Pastebin-sprunge/issues
  homepage: http://p3rl.org/App::Pastebin::sprunge
  repository: git://github.com/doherty/App-Pastebin-sprunge.git
version: 0.007
