---
abstract: 'application for pasting to and reading from sprunge.us'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Test::More: 0.82
  Test::Output: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pastebin-sprunge
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Getopt::Long: 0
  Pod::Usage: 0
  WWW::Pastebin::Sprunge::Create: 0
  WWW::Pastebin::Sprunge::Retrieve: 0
  perl: v5.10.1
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/App-Pastebin-sprunge/issues
  homepage: http://metacpan.org/release/App-Pastebin-sprunge/
  repository: git://github.com/doherty/App-Pastebin-sprunge.git
version: 0.010
